name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main  # CI: Run tests on PR to main branch
  push:
    branches:
      - main  # CD: Deploy app on merge to main

jobs:
  test:
    name: test
    runs-on: windows-latest

    steps:
      - name: Run Pytest
        run: pytest
        continue-on-error: false

  deploy:
    name: deploy
    needs: test  # Deploy only if tests pass
    if: github.ref == 'refs/heads/main'
    runs-on: windows-latests

    steps:


      - name: Deploy to Server
        run: |
          ssh user@your-server-ip <<EOF
            cd /path/to/your/app #ssh user1@ipaddress
            git pull origin main
            pip install -r requirements.txt
            systemctl restart fastapi.service
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
